version: "3.8"
services:
  backend:
    build: ./server
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    environment:
      - REDIS_HOST=redis
      - GROQ_API_KEY=${GROQ_API_KEY}
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
